site:
  about:
    siteName: 'xenji.com'
    subtitle: 'My two cent about tech, leadership, management and random things.'
    siteDescription: 'A resource for technology related articles, thoughts and sometimes gibberish.'

    avatar: '/assets/media/logo.jpg'

theme:
  social:
    facebook:
    twitter: 'xenji'
    instagram:
    github: 'xenji'
    other:
      - label: 'linkedin'
        link: 'https://www.linkedin.com/in/mariomueller/'
        icon: 'fa-tag'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About'
      itemId: 'xenji'
    - type: "pages"
      atRoot: true
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'
